server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.107.131
    virtual-host: /leyou
    username: leyou
    password: leyou
ols:
  sms:
    accessKeyId:  # accessKeyId
    accessKeySecret:  # AccessKeySecret
    signName: 在线商城 # 签名名称
    verifyCodeTemplate: SMS_187954853  # 模板名称
