server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/onlinestore?useUnicode=true&characterEncoding=UTF8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.107.131
  rabbitmq:
    host: 192.168.107.131
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.composer.user.pojo