server:
  port: 8082
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.107.131:9300
  jackson:
    default-property-inclusion: non_null #为空的字段不获取
  rabbitmq:
    host: 192.168.107.131
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: OLS.ITEM.EXCHANGE  #默认交换机
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5    #每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 15  #10秒不发送就过期
