server:
  port: 10086
spring:
  application:
    name: ols_registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false # 把自己注册到eureka服务列表
    fetch-registry: false # 拉取eureka服务信息
  server:
    enable-self-preservation: false  #关闭自我保护
    eviction-interval-timer-in-ms: 10000  #清理间隔